### ISSUE TITLE
能否支持web clipper剪辑网页？

### ISSUE THREAD

**Issue by elfzweik** [TankNee/Memocast#149]
能否支持web clipper剪辑网页？

**Comment by TankNee** [comment]
支持的，你直接用就好。

----------

该邮件从移动设备发送


--------------原始邮件--------------
发件人："elfzweik ***@***.***&gt;;
发送时间：2021年8月17日(星期二) 上午7:48
收件人："TankNee/Memocast" ***@***.***&gt;;
抄送："Subscribed ***@***.***&gt;;
主题：[TankNee/Memocast] 能否支持web clipper剪辑网页？ (#149)
-----------------------------------

 

 
能否支持web clipper剪辑网页？
 
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by elfzweik** [comment]
怎么用啊？web clipper要绑定笔记账号，是指选择为知笔记绑定吗？然后剪到为知笔记账号，再转到为知笔记私有服务器，momocast就能看到了是吗？

**Comment by TankNee** [comment]
> 怎么用啊？web clipper要绑定笔记账号，是指选择为知笔记绑定吗？然后剪到为知笔记账号，再转到为知笔记私有服务器，momocast就能看到了是吗？

![image](https://user-images.githubusercontent.com/43956168/129818015-0f7f1189-7097-4f74-a37a-6085e612755e.png)
zhi'jie直接在这里填入你的私有服务器地址就行。
