### ISSUE TITLE
feat: 能否提供个自动保存的功能

### ISSUE THREAD

**Issue by inhere** [TankNee/Memocast#155]

**Comment by TankNee** [comment]
可以，在计划中了。

**Comment by inhere** [comment]
👍  https://github.com/TankNee/Sponsor-Me 请你喝一杯奶茶了 😄

**Comment by TankNee** [comment]
收到啦，感谢支持。

----------

该邮件从移动设备发送


--------------原始邮件--------------
发件人："Inhere ***@***.***&gt;;
发送时间：2021年8月31日(星期二) 下午3:34
收件人："TankNee/Memocast" ***@***.***&gt;;
抄送："TankNee ***@***.***&gt;;"State change ***@***.***&gt;;
主题：Re: [TankNee/Memocast] feat: 能否提供个自动保存的功能 (#155)
-----------------------------------

 

 
  https://github.com/TankNee/Sponsor-Me 请你喝一杯奶茶了 
 
—
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
