### ISSUE TITLE
导出功能建议

### ISSUE THREAD

**Issue by SenLief** [TankNee/Memocast#160]
- 导出md文件，图片转换为base64，这样换到其他工具依然可以用。
- 希望增加pdf的导出

能否自定义字体？

**Comment by TankNee** [comment]
如果图片用base64的话文件会非常非常大，导致部分编辑器会打不开？
pdf的导出我打算用pandoc来支持，顺便支持一大波格式。
字体的话可以用主题文件来设置，自定义字体可以试试网络字体？iconfont之类的，内置多字体我暂时不打算支持。

----------

该邮件从移动设备发送


--------------原始邮件--------------
发件人："SenLief ***@***.***&gt;;
发送时间：2021年8月31日(星期二) 下午4:13
收件人："TankNee/Memocast" ***@***.***&gt;;
抄送："Subscribed ***@***.***&gt;;
主题：[TankNee/Memocast] 导出功能建议 (#160)
-----------------------------------

 

  
导出md文件，图片转换为base64，这样换到其他工具依然可以用。
 
希望增加pdf的导出
  
能否自定义字体？
 
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by SenLief** [comment]
但是现在导出md文件，会造成图片无法导出，不太友好啊，不过还行吧。

主题的了解了，我去试试。

**Comment by TankNee** [comment]
最新版已经可以导出图片了，你再试试？有问题我再看看。
不过只有为知服务器上的图片会被导出，其他的不会变动。

----------

该邮件从移动设备发送


--------------原始邮件--------------
发件人："SenLief ***@***.***&gt;;
发送时间：2021年8月31日(星期二) 下午4:20
收件人："TankNee/Memocast" ***@***.***&gt;;
抄送："TankNee ***@***.***&gt;;"Comment ***@***.***&gt;;
主题：Re: [TankNee/Memocast] 导出功能建议 (#160)
-----------------------------------

 

 
但是现在导出md文件，会造成图片无法导出，不太友好啊，不过还行吧。
 
主题的了解了，我去试试。
 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by TankNee** [comment]
了解了，是所有的都不行吗？还是个别的导出失败？

----------

该邮件从移动设备发送


--------------原始邮件--------------
发件人："SenLief ***@***.***&gt;;
发送时间：2021年8月31日(星期二) 下午4:33
收件人："TankNee/Memocast" ***@***.***&gt;;
抄送："TankNee ***@***.***&gt;;"Comment ***@***.***&gt;;
主题：Re: [TankNee/Memocast] 导出功能建议 (#160)
-----------------------------------

 

 我下载的就是最新版好像不行。导出图片是这样的。 
 <img src="memocast://memocast.app/d2656800-0a08-11ec-b468-196ba8cc2708/399aa9e0-0a0e-11ec-8f06-fb32d1291e8e/1630396963911-rci.jpg" title="" alt="" width="187"&gt; 
 
 
 从 Windows 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986&gt;发送 
 
 发件人: ***@***.***&gt; 
 发送时间: 2021年8月31日 16:32 
 收件人: ***@***.***&gt; 
 抄送: ***@***.***&gt;; State ***@***.***&gt; 
 主题: Re: [TankNee/Memocast] 导出功能建议 (#160) 
 
 最新版已经可以导出图片了，你再试试？有问题我再看看。 
 不过只有为知服务器上的图片会被导出，其他的不会变动。 
 
 ---------- 
 
 该邮件从移动设备发送 
 
 
 --------------原始邮件-------------- 
 发件人："SenLief ***@***.***&amp;gt;; 
 发送时间：2021年8月31日(星期二) 下午4:20 
 收件人："TankNee/Memocast" ***@***.***&amp;gt;; 
 抄送："TankNee ***@***.***&amp;gt;;"Comment ***@***.***&amp;gt;; 
 主题：Re: [TankNee/Memocast] 导出功能建议 (#160) 
 ----------------------------------- 
 
 
 
 
 但是现在导出md文件，会造成图片无法导出，不太友好啊，不过还行吧。 
 
 主题的了解了，我去试试。 
 
 ― 
 You are receiving this because you commented. 
 Reply to this email directly, view it on GitHub, or unsubscribe. 
 Triage notifications on the go with GitHub Mobile for iOS or Android. 
 
 ― 
 You are receiving this because you modified the open/close state. 
 Reply to this email directly, view it on GitHub<https://apac01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FTankNee%2FMemocast%2Fissues%2F160%23issuecomment-909021339&amp;data=04%7C01%7C%7C7677449bd80a4477032f08d96c59d720%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637659955382276625%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&amp;sdata=JqO0HGKyyA8dA5Tl%2Fmj8QHujPaGwfsFdMLOhOzkBxhM%3D&amp;reserved=0&gt;, or unsubscribe<https://apac01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAHT6YAYFJBLXTKX4XM2YJQ3T7SHRBANCNFSM5DDRNKJQ&amp;data=04%7C01%7C%7C7677449bd80a4477032f08d96c59d720%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637659955382276625%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&amp;sdata=YWFbJR8yGLb9dX4zd2z1KdPE%2FJGolIyvCuJk5PlqQtE%3D&amp;reserved=0&gt;. 
 
 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by SenLief** [comment]
我这的都不行。

从 Windows 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>发送

发件人: ***@***.***>
发送时间: 2021年8月31日 16:41
收件人: ***@***.***>
抄送: ***@***.***>; State ***@***.***>
主题: Re: [TankNee/Memocast] 导出功能建议 (#160)

了解了，是所有的都不行吗？还是个别的导出失败？

----------

该邮件从移动设备发送


--------------原始邮件--------------
发件人："SenLief ***@***.***&gt;;
发送时间：2021年8月31日(星期二) 下午4:33
收件人："TankNee/Memocast" ***@***.***&gt;;
抄送："TankNee ***@***.***&gt;;"Comment ***@***.***&gt;;
主题：Re: [TankNee/Memocast] 导出功能建议 (#160)
-----------------------------------



我下载的就是最新版好像不行。导出图片是这样的。
<img src="memocast://memocast.app/d2656800-0a08-11ec-b468-196ba8cc2708/399aa9e0-0a0e-11ec-8f06-fb32d1291e8e/1630396963911-rci.jpg" title="" alt="" width="187"&gt;


从 Windows 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986&gt;发送

发件人: ***@***.***&gt;
发送时间: 2021年8月31日 16:32
收件人: ***@***.***&gt;
抄送: ***@***.***&gt;; State ***@***.***&gt;
主题: Re: [TankNee/Memocast] 导出功能建议 (#160)

最新版已经可以导出图片了，你再试试？有问题我再看看。
不过只有为知服务器上的图片会被导出，其他的不会变动。

----------

该邮件从移动设备发送


--------------原始邮件--------------
发件人："SenLief ***@***.***&amp;gt;;
发送时间：2021年8月31日(星期二) 下午4:20
收件人："TankNee/Memocast" ***@***.***&amp;gt;;
抄送："TankNee ***@***.***&amp;gt;;"Comment ***@***.***&amp;gt;;
主题：Re: [TankNee/Memocast] 导出功能建议 (#160)
-----------------------------------




但是现在导出md文件，会造成图片无法导出，不太友好啊，不过还行吧。

主题的了解了，我去试试。

D
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

D
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub<https://apac01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FTankNee%2FMemocast%2Fissues%2F160%23issuecomment-909021339&amp;data=04%7C01%7C%7C7677449bd80a4477032f08d96c59d720%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637659955382276625%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&amp;sdata=JqO0HGKyyA8dA5Tl%2Fmj8QHujPaGwfsFdMLOhOzkBxhM%3D&amp;reserved=0&gt;, or unsubscribe<https://apac01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAHT6YAYFJBLXTKX4XM2YJQ3T7SHRBANCNFSM5DDRNKJQ&amp;data=04%7C01%7C%7C7677449bd80a4477032f08d96c59d720%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637659955382276625%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&amp;sdata=YWFbJR8yGLb9dX4zd2z1KdPE%2FJGolIyvCuJk5PlqQtE%3D&amp;reserved=0&gt;.


―
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

―

**Comment by TankNee** [comment]
收到，我再排查一下。

----------

该邮件从移动设备发送


--------------原始邮件--------------
发件人："SenLief ***@***.***&gt;;
发送时间：2021年8月31日(星期二) 下午4:42
收件人："TankNee/Memocast" ***@***.***&gt;;
抄送："TankNee ***@***.***&gt;;"Comment ***@***.***&gt;;
主题：Re: [TankNee/Memocast] 导出功能建议 (#160)
-----------------------------------

 

 我这的都不行。 
 
 从 Windows 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986&gt;发送 
 
 发件人: ***@***.***&gt; 
 发送时间: 2021年8月31日 16:41 
 收件人: ***@***.***&gt; 
 抄送: ***@***.***&gt;; State ***@***.***&gt; 
 主题: Re: [TankNee/Memocast] 导出功能建议 (#160) 
 
 了解了，是所有的都不行吗？还是个别的导出失败？ 
 
 ---------- 
 
 该邮件从移动设备发送 
 
 
 --------------原始邮件-------------- 
 发件人："SenLief ***@***.***&amp;gt;; 
 发送时间：2021年8月31日(星期二) 下午4:33 
 收件人："TankNee/Memocast" ***@***.***&amp;gt;; 
 抄送："TankNee ***@***.***&amp;gt;;"Comment ***@***.***&amp;gt;; 
 主题：Re: [TankNee/Memocast] 导出功能建议 (#160) 
 ----------------------------------- 
 
 
 
 我下载的就是最新版好像不行。导出图片是这样的。 
 <img src="memocast://memocast.app/d2656800-0a08-11ec-b468-196ba8cc2708/399aa9e0-0a0e-11ec-8f06-fb32d1291e8e/1630396963911-rci.jpg" title="" alt="" width="187"&amp;gt; 
 
 
 从 Windows 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986&amp;gt;发送 
 
 发件人: ***@***.***&amp;gt; 
 发送时间: 2021年8月31日 16:32 
 收件人: ***@***.***&amp;gt; 
 抄送: ***@***.***&amp;gt;; State ***@***.***&amp;gt; 
 主题: Re: [TankNee/Memocast] 导出功能建议 (#160) 
 
 最新版已经可以导出图片了，你再试试？有问题我再看看。 
 不过只有为知服务器上的图片会被导出，其他的不会变动。 
 
 ---------- 
 
 该邮件从移动设备发送 
 
 
 --------------原始邮件-------------- 
 发件人："SenLief ***@***.***&amp;amp;gt;; 
 发送时间：2021年8月31日(星期二) 下午4:20 
 收件人："TankNee/Memocast" ***@***.***&amp;amp;gt;; 
 抄送："TankNee ***@***.***&amp;amp;gt;;"Comment ***@***.***&amp;amp;gt;; 
 主题：Re: [TankNee/Memocast] 导出功能建议 (#160) 
 ----------------------------------- 
 
 
 
 
 但是现在导出md文件，会造成图片无法导出，不太友好啊，不过还行吧。 
 
 主题的了解了，我去试试。 
 
 D 
 You are receiving this because you commented. 
 Reply to this email directly, view it on GitHub, or unsubscribe. 
 Triage notifications on the go with GitHub Mobile for iOS or Android. 
 
 D 
 You are receiving this because you modified the open/close state. 
 Reply to this email directly, view it on GitHub<https://apac01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FTankNee%2FMemocast%2Fissues%2F160%23issuecomment-909021339&amp;amp;data=04%7C01%7C%7C7677449bd80a4477032f08d96c59d720%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637659955382276625%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&amp;amp;sdata=JqO0HGKyyA8dA5Tl%2Fmj8QHujPaGwfsFdMLOhOzkBxhM%3D&amp;amp;reserved=0&amp;gt;, or unsubscribe<https://apac01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAHT6YAYFJBLXTKX4XM2YJQ3T7SHRBANCNFSM5DDRNKJQ&amp;amp;data=04%7C01%7C%7C7677449bd80a4477032f08d96c59d720%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637659955382276625%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&amp;amp;sdata=YWFbJR8yGLb9dX4zd2z1KdPE%2FJGolIyvCuJk5PlqQtE%3D&amp;amp;reserved=0&amp;gt;. 
 
 
 ― 
 You are receiving this because you commented. 
 Reply to this email directly, view it on GitHub, or unsubscribe. 
 Triage notifications on the go with GitHub Mobile for iOS or Android. 
 
 ― 
 You are receiving this because you modified the open/close state. 
 Reply to this email directly, view it on GitHub<https://apac01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FTankNee%2FMemocast%2Fissues%2F160%23issuecomment-909027855&amp;data=04%7C01%7C%7C4392a2416b57414855da08d96c5b12f2%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637659960683476316%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&amp;sdata=OwppCMJ6bW1gaD0NwfJj7tNkfGxntJX4TXQAMom0S9Y%3D&amp;reserved=0&gt;, or unsubscribe<https://apac01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAHT6YAYTSTQL2WSFD5B4BN3T7SISDANCNFSM5DDRNKJQ&amp;data=04%7C01%7C%7C4392a2416b57414855da08d96c5b12f2%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637659960683486318%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&amp;sdata=FQhAFCNtYVar7gfixc7%2FyGnSeSlW0eIzQiHOTBCkkkM%3D&amp;reserved=0&gt;. 
 
 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by SenLief** [comment]
辛苦！

从 Windows 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>发送

发件人: ***@***.***>
发送时间: 2021年8月31日 16:44
收件人: ***@***.***>
抄送: ***@***.***>; State ***@***.***>
主题: Re: [TankNee/Memocast] 导出功能建议 (#160)

收到，我再排查一下。

----------

该邮件从移动设备发送


--------------原始邮件--------------
发件人："SenLief ***@***.***&gt;;
发送时间：2021年8月31日(星期二) 下午4:42
收件人："TankNee/Memocast" ***@***.***&gt;;
抄送："TankNee ***@***.***&gt;;"Comment ***@***.***&gt;;
主题：Re: [TankNee/Memocast] 导出功能建议 (#160)
-----------------------------------



我这的都不行。

从 Windows 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986&gt;发送

发件人: ***@***.***&gt;
发送时间: 2021年8月31日 16:41
收件人: ***@***.***&gt;
抄送: ***@***.***&gt;; State ***@***.***&gt;
主题: Re: [TankNee/Memocast] 导出功能建议 (#160)

了解了，是所有的都不行吗？还是个别的导出失败？

----------

该邮件从移动设备发送


--------------原始邮件--------------
发件人："SenLief ***@***.***&amp;gt;;
发送时间：2021年8月31日(星期二) 下午4:33
收件人："TankNee/Memocast" ***@***.***&amp;gt;;
抄送："TankNee ***@***.***&amp;gt;;"Comment ***@***.***&amp;gt;;
主题：Re: [TankNee/Memocast] 导出功能建议 (#160)
-----------------------------------



我下载的就是最新版好像不行。导出图片是这样的。
<img src="memocast://memocast.app/d2656800-0a08-11ec-b468-196ba8cc2708/399aa9e0-0a0e-11ec-8f06-fb32d1291e8e/1630396963911-rci.jpg" title="" alt="" width="187"&amp;gt;


从 Windows 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986&amp;gt;发送

发件人: ***@***.***&amp;gt;
发送时间: 2021年8月31日 16:32
收件人: ***@***.***&amp;gt;
抄送: ***@***.***&amp;gt;; State ***@***.***&amp;gt;
主题: Re: [TankNee/Memocast] 导出功能建议 (#160)

最新版已经可以导出图片了，你再试试？有问题我再看看。
不过只有为知服务器上的图片会被导出，其他的不会变动。

----------

该邮件从移动设备发送


--------------原始邮件--------------
发件人："SenLief ***@***.***&amp;amp;gt;;
发送时间：2021年8月31日(星期二) 下午4:20
收件人："TankNee/Memocast" ***@***.***&amp;amp;gt;;
抄送："TankNee ***@***.***&amp;amp;gt;;"Comment ***@***.***&amp;amp;gt;;
主题：Re: [TankNee/Memocast] 导出功能建议 (#160)
-----------------------------------




但是现在导出md文件，会造成图片无法导出，不太友好啊，不过还行吧。

主题的了解了，我去试试。

D
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

D
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub<https://apac01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FTankNee%2FMemocast%2Fissues%2F160%23issuecomment-909021339&amp;amp;data=04%7C01%7C%7C7677449bd80a4477032f08d96c59d720%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637659955382276625%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&amp;amp;sdata=JqO0HGKyyA8dA5Tl%2Fmj8QHujPaGwfsFdMLOhOzkBxhM%3D&amp;amp;reserved=0&amp;gt;, or unsubscribe<https://apac01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAHT6YAYFJBLXTKX4XM2YJQ3T7SHRBANCNFSM5DDRNKJQ&amp;amp;data=04%7C01%7C%7C7677449bd80a4477032f08d96c59d720%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637659955382276625%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&amp;amp;sdata=YWFbJR8yGLb9dX4zd2z1KdPE%2FJGolIyvCuJk5PlqQtE%3D&amp;amp;reserved=0&amp;gt;.


D
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

D
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub<https://apac01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FTankNee%2FMemocast%2Fissues%2F160%23issuecomment-909027855&amp;data=04%7C01%7C%7C4392a2416b57414855da08d96c5b12f2%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637659960683476316%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&amp;sdata=OwppCMJ6bW1gaD0NwfJj7tNkfGxntJX4TXQAMom0S9Y%3D&amp;reserved=0&gt;, or unsubscribe<https://apac01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAHT6YAYTSTQL2WSFD5B4BN3T7SISDANCNFSM5DDRNKJQ&amp;data=04%7C01%7C%7C4392a2416b57414855da08d96c5b12f2%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637659960683486318%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&amp;sdata=FQhAFCNtYVar7gfixc7%2FyGnSeSlW0eIzQiHOTBCkkkM%3D&amp;reserved=0&gt;.


―
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

―

**Comment by TankNee** [comment]
memocast的文件夹下有个叫logs的文件夹，里面有日志文件，你能找一下发给我嘛，可能比较难找，如果没有的话就算了

----------

该邮件从移动设备发送


--------------原始邮件--------------
发件人："SenLief ***@***.***&gt;;
发送时间：2021年8月31日(星期二) 下午4:45
收件人："TankNee/Memocast" ***@***.***&gt;;
抄送："TankNee ***@***.***&gt;;"Comment ***@***.***&gt;;
主题：Re: [TankNee/Memocast] 导出功能建议 (#160)
-----------------------------------

 

 辛苦！ 
 
 从 Windows 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986&gt;发送 
 
 发件人: ***@***.***&gt; 
 发送时间: 2021年8月31日 16:44 
 收件人: ***@***.***&gt; 
 抄送: ***@***.***&gt;; State ***@***.***&gt; 
 主题: Re: [TankNee/Memocast] 导出功能建议 (#160) 
 
 收到，我再排查一下。 
 
 ---------- 
 
 该邮件从移动设备发送 
 
 
 --------------原始邮件-------------- 
 发件人："SenLief ***@***.***&amp;gt;; 
 发送时间：2021年8月31日(星期二) 下午4:42 
 收件人："TankNee/Memocast" ***@***.***&amp;gt;; 
 抄送："TankNee ***@***.***&amp;gt;;"Comment ***@***.***&amp;gt;; 
 主题：Re: [TankNee/Memocast] 导出功能建议 (#160) 
 ----------------------------------- 
 
 
 
 我这的都不行。 
 
 从 Windows 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986&amp;gt;发送 
 
 发件人: ***@***.***&amp;gt; 
 发送时间: 2021年8月31日 16:41 
 收件人: ***@***.***&amp;gt; 
 抄送: ***@***.***&amp;gt;; State ***@***.***&amp;gt; 
 主题: Re: [TankNee/Memocast] 导出功能建议 (#160) 
 
 了解了，是所有的都不行吗？还是个别的导出失败？ 
 
 ---------- 
 
 该邮件从移动设备发送 
 
 
 --------------原始邮件-------------- 
 发件人："SenLief ***@***.***&amp;amp;gt;; 
 发送时间：2021年8月31日(星期二) 下午4:33 
 收件人："TankNee/Memocast" ***@***.***&amp;amp;gt;; 
 抄送："TankNee ***@***.***&amp;amp;gt;;"Comment ***@***.***&amp;amp;gt;; 
 主题：Re: [TankNee/Memocast] 导出功能建议 (#160) 
 ----------------------------------- 
 
 
 
 我下载的就是最新版好像不行。导出图片是这样的。 
 <img src="memocast://memocast.app/d2656800-0a08-11ec-b468-196ba8cc2708/399aa9e0-0a0e-11ec-8f06-fb32d1291e8e/1630396963911-rci.jpg" title="" alt="" width="187"&amp;amp;gt; 
 
 
 从 Windows 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986&amp;amp;gt;发送 
 
 发件人: ***@***.***&amp;amp;gt; 
 发送时间: 2021年8月31日 16:32 
 收件人: ***@***.***&amp;amp;gt; 
 抄送: ***@***.***&amp;amp;gt;; State ***@***.***&amp;amp;gt; 
 主题: Re: [TankNee/Memocast] 导出功能建议 (#160) 
 
 最新版已经可以导出图片了，你再试试？有问题我再看看。 
 不过只有为知服务器上的图片会被导出，其他的不会变动。 
 
 ---------- 
 
 该邮件从移动设备发送 
 
 
 --------------原始邮件-------------- 
 发件人："SenLief ***@***.***&amp;amp;amp;gt;; 
 发送时间：2021年8月31日(星期二) 下午4:20 
 收件人："TankNee/Memocast" ***@***.***&amp;amp;amp;gt;; 
 抄送："TankNee ***@***.***&amp;amp;amp;gt;;"Comment ***@***.***&amp;amp;amp;gt;; 
 主题：Re: [TankNee/Memocast] 导出功能建议 (#160) 
 ----------------------------------- 
 
 
 
 
 但是现在导出md文件，会造成图片无法导出，不太友好啊，不过还行吧。 
 
 主题的了解了，我去试试。 
 
 D 
 You are receiving this because you commented. 
 Reply to this email directly, view it on GitHub, or unsubscribe. 
 Triage notifications on the go with GitHub Mobile for iOS or Android. 
 
 D 
 You are receiving this because you modified the open/close state. 
 Reply to this email directly, view it on GitHub<https://apac01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FTankNee%2FMemocast%2Fissues%2F160%23issuecomment-909021339&amp;amp;amp;data=04%7C01%7C%7C7677449bd80a4477032f08d96c59d720%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637659955382276625%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&amp;amp;amp;sdata=JqO0HGKyyA8dA5Tl%2Fmj8QHujPaGwfsFdMLOhOzkBxhM%3D&amp;amp;amp;reserved=0&amp;amp;gt;, or unsubscribe<https://apac01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAHT6YAYFJBLXTKX4XM2YJQ3T7SHRBANCNFSM5DDRNKJQ&amp;amp;amp;data=04%7C01%7C%7C7677449bd80a4477032f08d96c59d720%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637659955382276625%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&amp;amp;amp;sdata=YWFbJR8yGLb9dX4zd2z1KdPE%2FJGolIyvCuJk5PlqQtE%3D&amp;amp;amp;reserved=0&amp;amp;gt;. 
 
 
 D 
 You are receiving this because you commented. 
 Reply to this email directly, view it on GitHub, or unsubscribe. 
 Triage notifications on the go with GitHub Mobile for iOS or Android. 
 
 D 
 You are receiving this because you modified the open/close state. 
 Reply to this email directly, view it on GitHub<https://apac01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FTankNee%2FMemocast%2Fissues%2F160%23issuecomment-909027855&amp;amp;data=04%7C01%7C%7C4392a2416b57414855da08d96c5b12f2%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637659960683476316%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&amp;amp;sdata=OwppCMJ6bW1gaD0NwfJj7tNkfGxntJX4TXQAMom0S9Y%3D&amp;amp;reserved=0&amp;gt;, or unsubscribe<https://apac01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAHT6YAYTSTQL2WSFD5B4BN3T7SISDANCNFSM5DDRNKJQ&amp;amp;data=04%7C01%7C%7C4392a2416b57414855da08d96c5b12f2%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637659960683486318%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&amp;amp;sdata=FQhAFCNtYVar7gfixc7%2FyGnSeSlW0eIzQiHOTBCkkkM%3D&amp;amp;reserved=0&amp;gt;. 
 
 
 ― 
 You are receiving this because you commented. 
 Reply to this email directly, view it on GitHub, or unsubscribe. 
 Triage notifications on the go with GitHub Mobile for iOS or Android. 
 
 ― 
 You are receiving this because you modified the open/close state. 
 Reply to this email directly, view it on GitHub<https://apac01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FTankNee%2FMemocast%2Fissues%2F160%23issuecomment-909030500&amp;data=04%7C01%7C%7Cd956abbaeed543e00a8108d96c5b8818%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637659962645880778%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&amp;sdata=BUOWyefy0L7CD90Ib9PSXyIrAOsfA%2FMukd%2FJT00st3Y%3D&amp;reserved=0&gt;, or unsubscribe<https://apac01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAHT6YA3WJC7V7UJW7GUMGLTT7SI6NANCNFSM5DDRNKJQ&amp;data=04%7C01%7C%7Cd956abbaeed543e00a8108d96c5b8818%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637659962645880778%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&amp;sdata=aZ%2Fc3%2B2jh560Isdxw7pqBffidkBQLn1xbYnGj%2B8p7Lw%3D&amp;reserved=0&gt;. 
 
 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by TankNee** [comment]
我都尝试了一下，mac和Windows都试过了，也没有复现你这个问题，所以我猜测可能是你的笔记比较特殊？或者你试试注册一个测试账号来导出笔记？

**Comment by SenLief** [comment]
难道是因为我是自建服务器的原因？明天我再试一下。




发自我的华为手机


-------- 原始邮件 --------
发件人： TankNee ***@***.***>
日期： 2021年8月31日周二 晚上10:00
收件人： TankNee/Memocast ***@***.***>
抄送： SenLief ***@***.***>, State change ***@***.***>
主 题： Re: [TankNee/Memocast] 导出功能建议 (#160)

我都尝试了一下，mac和Windows都试过了，也没有复现你这个问题，所以我猜测可能是你的笔记比较特殊？或者你试试注册一个测试账号来导出笔记？

―
