### ISSUE TITLE
提示“网络请求错误

### ISSUE THREAD

**Issue by 75re** [TankNee/Memocast#166]

**Comment by TankNee** [comment]
一般是网络问题，断网了之类的，一般来说重启Memocast就行，如果还是失败可以检查一下网络状况，网络也没问题的话能否发给我您的运行日志，日志在安装目录下的logs文件夹中。

----------

该邮件从移动设备发送


--------------原始邮件--------------
发件人："75re ***@***.***&gt;;
发送时间：2021年9月22日(星期三) 下午2:48
收件人："TankNee/Memocast" ***@***.***&gt;;
抄送："Subscribed ***@***.***&gt;;
主题：[TankNee/Memocast] 提示“网络请求错误 (#166)
-----------------------------------

 

 
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
